// FRONTEND FROZEN — BACKEND IS SOURCE OF TRUTH
/**
 * Chat with Aura
 * 
 * BACKEND AUTHORITY MODEL:
 * - All chat responses come from backend AI
 * - Frontend only sends user messages and renders responses
 * - NO local response generation or simulation
 */
import React, { useState, useRef, useEffect } from 'react';
import { Link } from 'react-router-dom';
import { motion, AnimatePresence } from 'framer-motion';
import { Send, ArrowLeft, Sparkles } from 'lucide-react';
import AIAvatar from '@/components/AIAvatar';
import ChatMessage from '@/components/ChatMessage';
import LoadingDots from '@/components/LoadingDots';
import api from '@/utils/api';

interface Message {
  id: number;
  content: string;
  isUser: boolean;
}

interface ChatResponse {
  message: string;
}

const Chat: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputValue, setInputValue] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const [auraState, setAuraState] = useState<'idle' | 'thinking' | 'speaking'>('idle');
  const [isInitialized, setIsInitialized] = useState(false);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  /**
   * BACKEND-DRIVEN INITIALIZATION
   * 
   * FRONTEND FROZEN — BACKEND AUTHORITY REQUIRED
   * Initial greeting comes from backend, not hardcoded.
   */
  useEffect(() => {
    const initializeChat = async () => {
      try {
        setAuraState('speaking');
        const response = await api.get<ChatResponse>('/chat/greeting');
        setMessages([{
          id: 1,
          content: response.data.message,
          isUser: false,
        }]);
      } catch {
        // Fallback only if backend is unavailable
        setMessages([{
          id: 1,
          content: "Hello! I'm Aura, your AI matching assistant. How can I help you today?",
          isUser: false,
        }]);
      } finally {
        setAuraState('idle');
        setIsInitialized(true);
      }
    };

    initializeChat();
  }, []);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  }, [messages, isTyping]);

  /**
   * BACKEND-DRIVEN MESSAGE HANDLING
   * 
   * FRONTEND FROZEN — BACKEND AUTHORITY REQUIRED
   * All responses are generated by backend AI.
   */
  const handleSendMessage = async () => {
    if (!inputValue.trim() || isTyping) return;

    const userMessage: Message = {
      id: Date.now(),
      content: inputValue,
      isUser: true,
    };

    setMessages((prev) => [...prev, userMessage]);
    const messageText = inputValue;
    setInputValue('');
    setIsTyping(true);
    setAuraState('thinking');

    try {
      const response = await api.post<ChatResponse>('/chat/message', {
        message: messageText,
      });

      setAuraState('speaking');
      const auraMessage: Message = {
        id: Date.now() + 1,
        content: response.data.message,
        isUser: false,
      };

      setMessages((prev) => [...prev, auraMessage]);
    } catch {
      // Error handling - show error message from backend or generic
      setAuraState('speaking');
      const errorMessage: Message = {
        id: Date.now() + 1,
        content: "I'm having trouble connecting right now. Please try again in a moment.",
        isUser: false,
      };
      setMessages((prev) => [...prev, errorMessage]);
    } finally {
      setIsTyping(false);
      setAuraState('idle');
    }
  };

  const handleKeyPress = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault();
      handleSendMessage();
    }
  };

  const handleSuggestionClick = (suggestion: string) => {
    setInputValue(suggestion);
  };

  const suggestionChips = ['Find me internships', 'What skills are in demand?', 'Show my match score', 'Interview tips'];

  return (
    <div className="min-h-screen flex flex-col">
      <motion.header 
        className="glass-strong border-b border-border sticky top-0 z-40" 
        initial={{ y: -50, opacity: 0 }} 
        animate={{ y: 0, opacity: 1 }}
      >
        <div className="container mx-auto px-4 py-4 flex items-center gap-4">
          <Link to="/dashboard" className="p-2 rounded-xl hover:bg-muted transition-colors">
            <ArrowLeft className="w-5 h-5" />
          </Link>
          <div className="flex items-center gap-3 flex-1">
            <AIAvatar state={auraState} size="sm" />
            <div>
              <h1 className="font-semibold">Chat with Aura</h1>
              <p className="text-sm text-muted-foreground">
                {isTyping ? 'Typing...' : 'Online'}
              </p>
            </div>
          </div>
          <Link to="/" className="flex items-center gap-2">
            <div className="w-8 h-8 rounded-lg gradient-bg flex items-center justify-center">
              <Sparkles className="w-5 h-5 text-primary-foreground" />
            </div>
          </Link>
        </div>
      </motion.header>

      <main className="flex-1 overflow-y-auto p-4 md:p-6">
        <div className="container mx-auto max-w-3xl space-y-6">
          <AnimatePresence>
            {messages.map((message) => (
              <ChatMessage 
                key={message.id} 
                content={message.content} 
                isUser={message.isUser} 
              />
            ))}
          </AnimatePresence>
          <AnimatePresence>
            {isTyping && (
              <motion.div 
                className="flex gap-3" 
                initial={{ opacity: 0, y: 10 }} 
                animate={{ opacity: 1, y: 0 }} 
                exit={{ opacity: 0, y: -10 }}
              >
                <AIAvatar state="thinking" size="sm" />
                <div className="glass rounded-2xl rounded-tl-sm px-4 py-3">
                  <LoadingDots />
                </div>
              </motion.div>
            )}
          </AnimatePresence>
          <div ref={messagesEndRef} />
        </div>
      </main>

      {isInitialized && messages.length <= 1 && (
        <motion.div 
          className="px-4 pb-2" 
          initial={{ opacity: 0, y: 20 }} 
          animate={{ opacity: 1, y: 0 }} 
          transition={{ delay: 0.3 }}
        >
          <div className="container mx-auto max-w-3xl">
            <div className="flex flex-wrap gap-2 justify-center">
              {suggestionChips.map((chip) => (
                <motion.button 
                  key={chip} 
                  className="px-4 py-2 rounded-full glass text-sm hover:bg-primary/10 transition-colors" 
                  whileHover={{ scale: 1.02 }} 
                  whileTap={{ scale: 0.98 }} 
                  onClick={() => handleSuggestionClick(chip)}
                >
                  {chip}
                </motion.button>
              ))}
            </div>
          </div>
        </motion.div>
      )}

      <motion.footer 
        className="glass-strong border-t border-border p-4" 
        initial={{ y: 50, opacity: 0 }} 
        animate={{ y: 0, opacity: 1 }}
      >
        <div className="container mx-auto max-w-3xl">
          <div className="flex gap-3 items-end">
            <input 
              type="text" 
              placeholder="Ask Aura anything..." 
              value={inputValue} 
              onChange={(e) => setInputValue(e.target.value)} 
              onKeyDown={handleKeyPress} 
              className="flex-1 px-4 py-3 rounded-xl border border-border bg-card/50 backdrop-blur-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-primary/50 focus:border-primary transition-all" 
              disabled={isTyping}
            />
            <motion.button 
              className="w-12 h-12 rounded-xl gradient-bg text-primary-foreground flex items-center justify-center disabled:opacity-50" 
              whileHover={{ scale: 1.05 }} 
              whileTap={{ scale: 0.95 }} 
              onClick={handleSendMessage} 
              disabled={!inputValue.trim() || isTyping}
            >
              <Send className="w-5 h-5" />
            </motion.button>
          </div>
        </div>
      </motion.footer>
    </div>
  );
};

export default Chat;
